version: '4'

services:
 mongodb:
  container_name: mongoProjeto
  image: mongo:latest
  environment:
   - MONGO_INITDB_ROOT_USERNAME=root
   - MONGO_INITDB_ROOT_PASSWORD=root
   - MONGO_INITDB_DATABASE=database
  restart: always
  ports:
    - 27017:27017
